#!/bin/sh
# The beginning of this script is both valid shell and valid python.
# This is necessary to reduce script run time in foreground
# It quickly fork-and-execs then exits
# I discovered the trick in Servo codebase: https://github.com/servo/servo/blob/c6ab60dbfc6da7b4f800c9e40893c8b58413960c/mach
'''python'  "$0" "$@" &
exit
'''

import os
import sys
import argparse
import logging
import urllib
import urllib2


parser = argparse.ArgumentParser()
parser.add_argument("--api-key", required=True, help="HistSync api key")
parser.add_argument("--user", required=True, help="Your GitHub/HistSync username")
parser.add_argument("--host", help="HistSync host", default="http://www.histsync.io")
parser.add_argument("--log-file", help="Log file. If not specified or empty, logging is disabled", default="")
parser.add_argument("command", help="Command to send")
args = parser.parse_args()

user = args.user
api_key = args.api_key
host = args.host
command_text = args.command


def upload_command(host, username, api_key, command_text):
    try:
        payload = {'api_key': api_key, 'command': command_text}
        req = urllib2.Request("{}/api/v0/user/{}/commands".format(host, username), urllib.urlencode(payload))
        urllib2.urlopen(req)
    except Exception as e:
        logging.exception(e)


if args.log_file:
    logging.basicConfig(filename=args.log_file, level=logging.DEBUG, format='%(asctime)s - %(process)d - %(name)s - %(levelname)s - %(message)s')
else:
    logging.disable(logging.CRITICAL)

upload_command(host, user, api_key, command_text)
