"""empty message

Revision ID: 10759d3db3c5
Revises: 2debffafb04
Create Date: 2015-05-19 21:54:14.412470

"""

# revision identifiers, used by Alembic.
revision = '10759d3db3c5'
down_revision = '2debffafb04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars_users')
    ### end Alembic commands ###
