"""empty message

Revision ID: 154b73f4e615
Revises: bba5d64fa32
Create Date: 2015-05-07 23:01:00.591160

"""

# revision identifiers, used by Alembic.
revision = '154b73f4e615'
down_revision = 'bba5d64fa32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'command', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'command', type_='foreignkey')
    op.drop_column('command', 'user_id')
    ### end Alembic commands ###
