"""empty message

Revision ID: 2debffafb04
Revises: 52d5be321d91
Create Date: 2015-05-10 21:23:04.500303

"""

# revision identifiers, used by Alembic.
revision = '2debffafb04'
down_revision = '52d5be321d91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('another_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'another_id')
    ### end Alembic commands ###
