"""empty message

Revision ID: 2f861c38002a
Revises: 10759d3db3c5
Create Date: 2015-05-19 23:04:59.635637

"""

# revision identifiers, used by Alembic.
revision = '2f861c38002a'
down_revision = '10759d3db3c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('time_shared', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'time_shared')
    ### end Alembic commands ###
