"""empty message

Revision ID: 35fb0cace7e8
Revises: 2f861c38002a
Create Date: 2015-06-13 20:15:08.609353

"""

# revision identifiers, used by Alembic.
revision = '35fb0cace7e8'
down_revision = '2f861c38002a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'description')
    ### end Alembic commands ###
