"""empty message

Revision ID: 4f42ff5e2c2
Revises: 154b73f4e615
Create Date: 2015-05-07 23:35:07.846962

"""

# revision identifiers, used by Alembic.
revision = '4f42ff5e2c2'
down_revision = '154b73f4e615'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'api_key')
    ### end Alembic commands ###
