"""empty message

Revision ID: 52d5be321d91
Revises: 4f42ff5e2c2
Create Date: 2015-05-08 20:29:49.436808

"""

# revision identifiers, used by Alembic.
revision = '52d5be321d91'
down_revision = '4f42ff5e2c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('is_public', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'is_public')
    ### end Alembic commands ###
