"""empty message

Revision ID: 54fc9c08c874
Revises: None
Create Date: 2015-05-06 21:20:20.638388

"""

# revision identifiers, used by Alembic.
revision = '54fc9c08c874'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('time_added', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'time_added')
    ### end Alembic commands ###
